### ISSUE TITLE
exited: WowzaStreamingEnginge (exit status 0, not expected)

### ISSUE THREAD

**Issue by nielsswinkels** [Cyconet/docker-wowza-streaming-engine-persistent#2]
I get this error in the logs:
![image](https://user-images.githubusercontent.com/5718354/53098154-58b69900-3523-11e9-891a-5513b5fcad1b.png)

this was the command I used to start it:
![image](https://user-images.githubusercontent.com/5718354/53098231-7ab01b80-3523-11e9-8aec-b5df0db4c972.png)

Any idea what is going wrong? This has worked before..

**Comment by waja** [comment]
> Any idea what is going wrong? This has worked before..

Actually I'm not using this image anymore. But I would try to have a look into the Logfiles. You set it via WSE_LOG_DIR and try to bind mount it to you host or you can enter the running container and have a look there...
